name: gasapp
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  easy_localization: ^3.0.7
  get_it: ^8.0.3
  dio: ^5.7.0
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  lottie: ^3.3.0
  flash: ^3.1.1
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  firebase_core: ^3.9.0
  shared_preferences: ^2.3.4
  flutter_widget_from_html: ^0.15.3
  dotted_border: ^2.1.0
  url_launcher: ^6.3.1
  photo_view: ^0.15.0
  flutter_rating_bar: ^4.0.1
  myfatoorah_flutter: ^3.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0




flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/lottie/
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json


  fonts:
    - family: IBM-
      fonts:
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/semiBold.ttf
          weight: 600
        - asset: assets/fonts/medium.ttf
          weight: 500
        - asset: assets/fonts/regular.ttf
          weight: 400
        - asset: assets/fonts/light.ttf
          weight: 300