import 'package:get_it/get_it.dart';

import '../../features/agent/car_info/controller/cubit.dart';
import '../../features/agent/home/controller/home_cubit.dart';
import '../../features/agent/order_details/cubit/order_details_cubit.dart';
import '../../features/agent/orders/cubit/orders_cubit.dart';
import '../../features/agent/select_merchent/cubit/select_merchent_cubit.dart';
import '../../features/auth/complete_data/controller/complete_data_cubit.dart';
import '../../features/auth/forget_password/controller/forget_password_cubit.dart';
import '../../features/auth/login/controller/login_cubit.dart';
import '../../features/auth/logout/logout_cubit.dart';
import '../../features/auth/register/controller/register_cubit.dart';
import '../../features/auth/reset_password/controller/reset_password_cubit.dart';
import '../../features/auth/verify_phone/controller/verify_phone_bloc.dart';
import '../../features/client/addresses/controller/cubit.dart';
import '../../features/client/cart/controller/cubit.dart';
import '../../features/client/company_details/controller/cubit.dart';
import '../../features/client/factories_accessories/controller/factories_cubit.dart';
import '../../features/client/factory_details/controller/cubit.dart';
import '../../features/client/gas_distributing/controller/cubit.dart';
import '../../features/client/home/controller/cubit.dart';
import '../../features/client/maintenance_supply/controller/cubit.dart';
import '../../features/client/orders/controller/order_details/cubit.dart';
import '../../features/client/orders/controller/orders/cubit.dart';
import '../../features/client/product_details/controller/cubit.dart';
import '../../features/client/refill/controller/cubit.dart';
import '../../features/product_agent/home/controller/home_cubit.dart';
import '../../features/product_agent/order_details/cubit/order_details_cubit.dart';
import '../../features/product_agent/orders/cubit/orders_cubit.dart';
import '../../features/shared/controller/cancel_reasons/cubit.dart';
import '../../features/shared/controller/countries/cubit.dart';
import '../../features/shared/controller/google_map_search/bloc.dart';
import '../../features/shared/controller/payment/bloc.dart';
import '../../features/shared/controller/upload_attachment/attachment_cubit.dart';
import '../../features/shared/pages/contact_us/controller/contact_us_cubit.dart';
import '../../features/shared/pages/edit_profile/controller/edit_profile_cubit.dart';
import '../../features/shared/pages/faq/controller/cubit.dart';
import '../../features/shared/pages/navbar/cubit/navbar_cubit.dart';
import '../../features/shared/pages/notifications/cubit/notifications_cubit.dart';
import '../../features/shared/pages/order_counts/controller/cubit.dart';
import '../../features/shared/pages/profits/controller/cubit.dart';
import '../../features/shared/pages/settings/controller/cubit.dart';
import '../../features/shared/pages/static_pages/controller/cubit.dart';
import '../../features/shared/pages/wallet/controller/wallet_cubit.dart';
import '../../features/technician/home/controller/home_cubit.dart';
import '../../features/technician/order_details/cubit/order_details_cubit.dart';
import '../../features/technician/orders/cubit/orders_cubit.dart';
import '../utils/location_service.dart';
import 'location_tracking_service.dart';

final sl = GetIt.instance;

class ServicesLocator {
  void init() {
    sl.registerFactory(() => LoginCubit());
    sl.registerFactory(() => LogoutCubit());
    sl.registerFactory(() => RegisterCubit());
    sl.registerFactory(() => CompleteDataCubit());
    sl.registerFactory(() => ForgetPasswordCubit());
    sl.registerFactory(() => ResetPasswordCubit());
    sl.registerFactory(() => CountriesCubit());
    sl.registerFactory(() => VerifyPhoneCubit());
    sl.registerFactory(() => UploadAttachmentCubit());
    sl.registerFactory(() => EditProfileCubit());
    sl.registerFactory(() => SettingsCubit());
    sl.registerFactory(() => StaticCubit());
    sl.registerFactory(() => ContactUsCubit());
    sl.registerFactory(() => FaqCubit());
    sl.registerFactory(() => FreeAgentCarInfoCubit());
    sl.registerFactory(() => ProfitsCubit());
    sl.registerFactory(() => OrderCountsCubit());
    sl.registerFactory(() => WalletCubit());
    sl.registerLazySingleton(() => ClientHomeCubit());
    sl.registerLazySingleton(() => AddressesCubit());
    sl.registerLazySingleton(() => ClientDistributeGasCubit());
    sl.registerFactory(() => ClientRefillCubit());
    sl.registerFactory(() => ClientMaintenanceSupplyCubit());
    sl.registerLazySingleton(() => CompanyDetailsCubit());
    sl.registerLazySingleton(() => LocationService());
    sl.registerLazySingleton(() => LocationTrackingService.instance);
    sl.registerFactory(() => GoogleMapSearchBloc());
    sl.registerFactory(() => ClientOrdersCubit());
    sl.registerFactory(() => ClientFactoriesAccessoriesCubit());
    sl.registerFactory(() => FactoryDetailsCubit());
    sl.registerFactory(() => ProductDetailsCubit());
    sl.registerLazySingleton(() => CartCubit());
    sl.registerFactory(() => ClientOrderDetailsCubit());
    sl.registerFactory(() => AgentHomeCubit());
    sl.registerLazySingleton(() => NavbarCubit());
    sl.registerFactory(() => NotificationsCubit());
    sl.registerFactory(() => AgentOrdersCubit());
    sl.registerFactory(() => AgentOrderDetailsCubit());
    sl.registerFactory(() => SelectMerchentCubit());
    sl.registerFactory(() => TechnicianHomeCubit());
    sl.registerFactory(() => TechnicianOrdersCubit());
    sl.registerFactory(() => TechnicianOrderDetailsCubit());
    sl.registerFactory(() => ProductAgentHomeCubit());
    sl.registerFactory(() => ProductAgentOrderDetailsCubit());
    sl.registerFactory(() => ProductAgentOrdersCubit());
    sl.registerFactory(() => CancelReasonsCubit());
    sl.registerFactory(() => PaymentInfoBloc());
  }
}
